### ISSUE TITLE
Agent gets stuck on `post_transaction_round` to update market address on market approval server.

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/market-creator#82]
Agent gets stuck on `post_transaction_round` to update market address on market approval server.

```
2024-01-05 13:29:21.924	
2024-01-05T12:29:21.779782933Z stdout F [2024-01-05 12:29:21,779] [INFO] [agent] 'post_transaction_round' round is done with event: Event.ERROR
2024-01-05 13:29:21.924	
2024-01-05T12:29:21.759143865Z stdout F [2024-01-05 12:29:21,759] [INFO] Created a new local deadline for the next `begin_block` request from the Tendermint node: 2024-01-05 12:30:21.759055
2024-01-05 13:29:21.924	
2024-01-05T12:29:21.759067162Z stdout F [2024-01-05 12:29:21,759] [INFO] [agent] no pending timeout, move time forward



2024-01-05 13:29:21.924	
2024-01-05T12:29:21.759045389Z stdout F [2024-01-05 12:29:21,758] [INFO] [agent] current AbciApp time: 2024-01-05 12:29:19.710402
2024-01-05 13:29:21.924	
2024-01-05T12:29:21.758791104Z stdout F [2024-01-05 12:29:21,758] [INFO] [agent] arrived block with timestamp: 2024-01-05 12:29:20.729118
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.89855559Z stdout F ,message_id=-1,performative=error,target=1)
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898550206Z stdout F IndexError: tuple index out of range
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898544181Z stdout F 
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898540725Z stdout F             ~~~~^^^
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898537704Z stdout F     event = logs[0]
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898534146Z stdout F   File "/root/agent/vendor/valory/contracts/fpmm_deterministic_factory/contract.py", line 224, in parse_market_creation_event
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898528731Z stdout F 
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.898501324Z stdout F [2024-01-05 12:29:20,898] [WARNING] [agent] parse_market_creation_event unsuccessful!: Message(sender=valory/ledger:0.19.0,to=valory/market_maker_abci:0.1.0,code=500,data=b'',dialogue_reference=('262ca3cf65677d30ebd9fd837b1e81c6e887908757797f2be6c6bec4b8ee95ae', 'ba10dc875af6300af495a7d3fba0d8bb3698b89a8f5c9cd91808488493bf5acc'),message=Traceback (most recent call last):
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.820039616Z stdout F [2024-01-05 12:29:20,819] [INFO] [agent] Handling settled tx hash 0xfc3cfa4cbc57ed980bf064605fe3437ac649a29fe7d3b0dd7c15341515f579a9. For market with id 77411169-974d-4fee-971e-a3208672d780. 
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.819371539Z stdout F [2024-01-05 12:29:20,819] [INFO] [agent] Entered in the 'post_transaction_behaviour' behaviour
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.81369879Z stdout F [2024-01-05 12:29:20,813] [INFO] [agent] Entered in the 'post_transaction_round' round for period 510
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.813174201Z stdout F [2024-01-05 12:29:20,812] [INFO] [agent] 'post_transaction_round' round is done with event: Event.ERROR
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.792570468Z stdout F [2024-01-05 12:29:20,792] [INFO] Created a new local deadline for the next `begin_block` request from the Tendermint node: 2024-01-05 12:30:20.792495
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.792543731Z stdout F [2024-01-05 12:29:20,792] [INFO] [agent] no pending timeout, move time forward
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.792346287Z stdout F [2024-01-05 12:29:20,792] [INFO] [agent] current AbciApp time: 2024-01-05 12:29:18.690371
2024-01-05 13:29:20.922	
2024-01-05T12:29:20.792178222Z stdout F [2024-01-05 12:29:20,791] [INFO] [agent] arrived block with timestamp: 2024-01-05 12:29:19.710402
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835187209Z stdout F ,message_id=-1,performative=error,target=1)
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835184217Z stdout F IndexError: tuple index out of range
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835180958Z stdout F 
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835178254Z stdout F             ~~~~^^^
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835175236Z stdout F     event = logs[0]
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835171949Z stdout F   File "/root/agent/vendor/valory/contracts/fpmm_deterministic_factory/contract.py", line 224, in parse_market_creation_event
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835167008Z stdout F 
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.835147795Z stdout F [2024-01-05 12:29:19,834] [WARNING] [agent] parse_market_creation_event unsuccessful!: Message(sender=valory/ledger:0.19.0,to=valory/market_maker_abci:0.1.0,code=500,data=b'',dialogue_reference=('127452714b2822ba577ea5d5c9adc7dd164ebc469727953b8e5cf7119729a6ef', '8600a5c177089fc17fd54c246eaf2ba959a258594a182713c4332906701cc696'),message=Traceback (most recent call last):
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.763785802Z stdout F [2024-01-05 12:29:19,763] [INFO] [agent] Handling settled tx hash 0xfc3cfa4cbc57ed980bf064605fe3437ac649a29fe7d3b0dd7c15341515f579a9. For market with id 77411169-974d-4fee-971e-a3208672d780. 
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.763115859Z stdout F [2024-01-05 12:29:19,762] [INFO] [agent] Entered in the 'post_transaction_behaviour' behaviour
2024-01-05 13:29:19.920	
2024-01-05T12:29:19.751768617Z stdout F [2024-01-05 12:29:19,751] [INFO] [agent] Entered in the 'post_transaction_round' round for period 510
```

**Comment by jmoreira-valory** [comment]
Addressed on #82
